### ISSUE TITLE
Bot removes unverified role but does not add participant role & change nickname

### ISSUE THREAD

**Issue by yokehan** [buildingblocs/verification-bot#7]
After the user enters the necessary commands in the #verification channel, the bot will remove their unverified role but will not add the participant role and change the user's nickname. 

User will be left with no roles and their normal discord username. This allows them to view all the channels that are visible to the @everyone role.

However, when an organiser manually adds the participant role to the user, the user's nickname will change to their originally inputted nickname in the #verification channel.

**Comment by ThinkerPal** [comment]
likely an issue related to #6 - will observe the rollout of that hotfix to see if things change

will leave this open for now, though

**Comment by ThinkerPal** [comment]
seems to be fixed so I'll close this
